version: '3.8'
services:
  kvm:
    build: .
    privileged: true
    network_mode: host
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    restart: always
    
    netboot:
    image: linuxserver/netbootxyz
    container_name: netbootxyz
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./netboot/config:/config
      - ./netboot/assets:/assets
    restart: unless-stopped