services:
  kvm:
    image: wombat-kvm-local
    build: .
    container_name: wombat-kvm
    restart: always
    ports:
      - "5000:5000"  # Flask Web UI
      - "8080:8080"  # uStreamer Video
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0" # Your CH340 Bridge
    privileged: true