services:
  wombat-kvm:
    build: .
    container_name: wombat-kvm
    restart: always
    privileged: true
    network_mode: host
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    ports:
      - "5000:5000"
      - "8000:8000"